use std::collections::HashMap;

use rusqlite::Connection;

use crate::core::analysis::{analyze_session, AnalysisResult};
use crate::core::db::{self, CommandFilter, CommandRow};
use crate::core::fmt::ascii::{format_relative_time, parse_duration_ago};
use crate::core::fmt::markdown;
use crate::error::Error;

pub struct AgentContextArgs<'a> {
    pub format: &'a str,
    pub since: Option<&'a str>,
    pub max_tokens: Option<usize>,
}

pub fn run(conn: &Connection, args: &AgentContextArgs) -> Result<(), Error> {
    let git_repo = resolve_git_repo();
    let commands = fetch_project_commands(conn, &git_repo, args.since)?;

    if commands.is_empty() {
        println!("No RedTrail history for this directory yet.");
        return Ok(());
    }

    let sessions = group_by_agent_session(&commands);
    let recent_sessions = select_recent_sessions(&sessions, args.since);

    let analyses: Vec<(String, Vec<CommandRow>, AnalysisResult)> = recent_sessions
        .into_iter()
        .map(|(id, cmds)| {
            let analysis = analyze_session(&cmds);
            (id, cmds, analysis)
        })
        .collect();

    let output = match args.format {
        "json" => render_json(&git_repo, &commands, &analyses),
        _ => render_markdown(&git_repo, &commands, &analyses),
    };

    let output = match args.max_tokens {
        Some(budget) => trim_to_budget(&output, budget),
        None => output,
    };

    print!("{output}");
    Ok(())
}

/// Resolve the git repo root for the current directory.
fn resolve_git_repo() -> Option<String> {
    std::process::Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()
        .and_then(|out| {
            if out.status.success() {
                Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
            } else {
                std::env::current_dir()
                    .ok()
                    .and_then(|p| p.canonicalize().ok().or(Some(p)))
                    .and_then(|p| p.to_str().map(String::from))
            }
        })
}

/// Fetch all commands for this project, optionally filtered by --since.
fn fetch_project_commands(
    conn: &Connection,
    git_repo: &Option<String>,
    since: Option<&str>,
) -> Result<Vec<CommandRow>, Error> {
    let since_ts = match since {
        Some(dur) => Some(parse_duration_ago(dur)?),
        None => None,
    };

    db::get_commands(
        conn,
        &CommandFilter {
            git_repo: git_repo.as_deref(),
            since: since_ts,
            limit: Some(10000),
            ..Default::default()
        },
    )
}

/// Group commands by agent_session_id (falling back to session_id).
/// Returns groups sorted by most recent first (max timestamp in each group).
fn group_by_agent_session(commands: &[CommandRow]) -> Vec<(String, Vec<CommandRow>)> {
    let mut groups: HashMap<String, Vec<CommandRow>> = HashMap::new();

    for cmd in commands {
        let key = cmd
            .agent_session_id
            .as_deref()
            .unwrap_or(&cmd.session_id)
            .to_string();
        groups.entry(key).or_default().push(cmd.clone());
    }

    let mut groups: Vec<(String, Vec<CommandRow>)> = groups.into_iter().collect();

    // Sort by most recent first (max timestamp_start in each group)
    groups.sort_by(|a, b| {
        let max_a = a.1.iter().map(|c| c.timestamp_start).max().unwrap_or(0);
        let max_b = b.1.iter().map(|c| c.timestamp_start).max().unwrap_or(0);
        max_b.cmp(&max_a)
    });

    groups
}

/// Select sessions: if --since was provided, use all groups;
/// otherwise take the 3 most recent.
fn select_recent_sessions(
    sessions: &[(String, Vec<CommandRow>)],
    since: Option<&str>,
) -> Vec<(String, Vec<CommandRow>)> {
    let limit = if since.is_some() {
        sessions.len()
    } else {
        3
    };
    sessions
        .iter()
        .take(limit)
        .map(|(id, cmds)| (id.clone(), cmds.clone()))
        .collect()
}

/// Render the context document as markdown.
fn render_markdown(
    git_repo: &Option<String>,
    all_commands: &[CommandRow],
    analyses: &[(String, Vec<CommandRow>, AnalysisResult)],
) -> String {
    let mut out = String::new();

    out.push_str("# Project Context (generated by RedTrail)\n\n");

    // Current State
    out.push_str("## Current State\n");
    if let Some(repo) = git_repo {
        out.push_str(&format!("- **Directory:** `{}`\n", markdown::escape(repo)));
    }
    // Branch from most recent analysis
    if let Some((_, _, a)) = analyses.first()
        && let Some(branch) = &a.branch
    {
        out.push_str(&format!("- **Branch:** `{}`\n", markdown::escape(branch)));
    }
    // Last activity from most recent command across all data
    if let Some(latest_ts) = all_commands.iter().map(|c| c.timestamp_start).max() {
        out.push_str(&format!("- **Last activity:** {}\n", format_relative_time(latest_ts)));
    }
    out.push('\n');

    // Recent Agent Sessions
    if !analyses.is_empty() {
        out.push_str("## Recent Agent Sessions\n\n");
        for (i, (_session_id, _cmds, a)) in analyses.iter().enumerate() {
            let idx = i + 1;
            let duration = format_duration_human(a.duration_seconds);

            // Session timing from earliest command
            let session_time = if let Some(dir) = &a.directory {
                let _ = dir; // use directory for context if needed
                let earliest = _cmds.iter().map(|c| c.timestamp_start).min().unwrap_or(0);
                format_relative_time(earliest)
            } else {
                let earliest = _cmds.iter().map(|c| c.timestamp_start).min().unwrap_or(0);
                format_relative_time(earliest)
            };

            out.push_str(&format!("### Session {idx} ({session_time}, {duration})\n"));

            // Files modified
            let files: Vec<&str> = a
                .files_modified
                .iter()
                .chain(a.files_created.iter())
                .map(|s| s.as_str())
                .collect();
            if !files.is_empty() {
                let file_list = files.join(", ");
                out.push_str(&format!("Modified: {}\n", markdown::escape(&file_list)));
            }

            // Outcome
            let outcome = if a.tests_failed > 0 {
                format!("{} test(s) failing.", a.tests_failed)
            } else if a.test_runs > 0 {
                "All tests passing.".to_string()
            } else if a.total_errors == 0 {
                "Completed without errors.".to_string()
            } else if a.errors_resolved == a.total_errors {
                format!("All {} error(s) resolved.", a.total_errors)
            } else {
                format!(
                    "{} error(s), {} resolved.",
                    a.total_errors, a.errors_resolved
                )
            };
            out.push_str(&format!("Outcome: {outcome}\n"));

            // Errors resolved
            let resolved: Vec<&_> = a.error_sequences.iter().filter(|s| s.resolved).collect();
            if !resolved.is_empty() {
                out.push_str("Errors resolved:");
                for seq in &resolved {
                    out.push_str(&format!(
                        " `{}` -> `{}`",
                        markdown::escape(&seq.failing_command),
                        markdown::escape(
                            seq.resolution_command.as_deref().unwrap_or("(manual fix)")
                        )
                    ));
                }
                out.push('\n');
            }
            out.push('\n');
        }
    }

    // Known Errors & Fixes (deduplicated across all sessions)
    let all_error_fixes: Vec<_> = analyses
        .iter()
        .flat_map(|(_, _, a)| a.error_sequences.iter())
        .filter(|s| s.resolved)
        .collect();

    if !all_error_fixes.is_empty() {
        out.push_str("## Known Errors & Fixes\n");
        let mut seen: HashMap<String, usize> = HashMap::new();
        let mut entries: Vec<(String, String, usize)> = Vec::new();
        for seq in &all_error_fixes {
            let key = format!(
                "{} -> {}",
                seq.failing_command,
                seq.resolution_command.as_deref().unwrap_or("(manual fix)")
            );
            let count = seen.entry(key.clone()).or_insert(0);
            *count += 1;
            if *count == 1 {
                entries.push((
                    seq.failing_command.clone(),
                    seq.resolution_command
                        .as_deref()
                        .unwrap_or("(manual fix)")
                        .to_string(),
                    0, // placeholder, we'll fill below
                ));
            }
        }
        // Fill counts
        for entry in &mut entries {
            let key = format!("{} -> {}", entry.0, entry.1);
            entry.2 = seen[&key];
        }
        for (fail, fix, count) in &entries {
            out.push_str(&format!(
                "- `{}` -> `{}` (seen {} time(s))\n",
                markdown::escape(fail),
                markdown::escape(fix),
                count,
            ));
        }
        out.push('\n');
    }

    // Project Workflow (top 15 commands by binary+subcommand)
    let freq = command_frequencies(all_commands);
    if !freq.is_empty() {
        out.push_str("## Project Workflow\nMost used commands:\n");
        for (cmd_label, count) in freq.iter().take(15) {
            out.push_str(&format!("- `{}` (x{})\n", markdown::escape(cmd_label), count));
        }
        out.push('\n');
    }

    // Unresolved Issues
    let unresolved: Vec<_> = analyses
        .iter()
        .flat_map(|(_, _, a)| a.error_sequences.iter())
        .filter(|s| !s.resolved)
        .collect();

    out.push_str("## Unresolved Issues\n");
    if unresolved.is_empty() {
        out.push_str("- None currently\n");
    } else {
        for seq in &unresolved {
            out.push_str(&format!(
                "- `{}`: {}\n",
                markdown::escape(&seq.failing_command),
                markdown::escape(&seq.error_message),
            ));
        }
    }
    out.push('\n');

    out
}

/// Render the context document as JSON.
fn render_json(
    git_repo: &Option<String>,
    all_commands: &[CommandRow],
    analyses: &[(String, Vec<CommandRow>, AnalysisResult)],
) -> String {
    let sessions: Vec<serde_json::Value> = analyses
        .iter()
        .map(|(session_id, cmds, a)| {
            let earliest = cmds.iter().map(|c| c.timestamp_start).min().unwrap_or(0);
            let files: Vec<&str> = a
                .files_modified
                .iter()
                .chain(a.files_created.iter())
                .map(|s| s.as_str())
                .collect();
            let resolved: Vec<serde_json::Value> = a
                .error_sequences
                .iter()
                .filter(|s| s.resolved)
                .map(|s| {
                    serde_json::json!({
                        "failing_command": s.failing_command,
                        "resolution": s.resolution_command,
                    })
                })
                .collect();
            serde_json::json!({
                "session_id": session_id,
                "started": earliest,
                "duration_seconds": a.duration_seconds,
                "total_commands": a.total_commands,
                "files_modified": files,
                "errors_total": a.total_errors,
                "errors_resolved": a.errors_resolved,
                "test_runs": a.test_runs,
                "tests_passed": a.tests_passed,
                "tests_failed": a.tests_failed,
                "error_fix_sequences": resolved,
            })
        })
        .collect();

    let freq = command_frequencies(all_commands);
    let top_commands: Vec<serde_json::Value> = freq
        .iter()
        .take(15)
        .map(|(cmd, count)| serde_json::json!({"command": cmd, "count": count}))
        .collect();

    let unresolved: Vec<serde_json::Value> = analyses
        .iter()
        .flat_map(|(_, _, a)| a.error_sequences.iter())
        .filter(|s| !s.resolved)
        .map(|s| {
            serde_json::json!({
                "failing_command": s.failing_command,
                "error_message": s.error_message,
            })
        })
        .collect();

    let branch = analyses
        .first()
        .and_then(|(_, _, a)| a.branch.clone());
    let latest_ts = all_commands.iter().map(|c| c.timestamp_start).max();

    let val = serde_json::json!({
        "directory": git_repo,
        "branch": branch,
        "last_activity": latest_ts,
        "sessions": sessions,
        "top_commands": top_commands,
        "unresolved_issues": unresolved,
    });

    serde_json::to_string_pretty(&val).unwrap_or_default() + "\n"
}

/// Compute command frequencies by binary+subcommand.
fn command_frequencies(commands: &[CommandRow]) -> Vec<(String, usize)> {
    let mut freq: HashMap<String, usize> = HashMap::new();
    for cmd in commands {
        let binary = match cmd.command_binary.as_deref() {
            Some(b) if !b.is_empty() => b,
            _ => continue,
        };
        let label = match &cmd.command_subcommand {
            Some(sub) => format!("{binary} {sub}"),
            None => binary.to_string(),
        };
        *freq.entry(label).or_insert(0) += 1;
    }
    let mut sorted: Vec<(String, usize)> = freq.into_iter().collect();
    sorted.sort_by(|a, b| b.1.cmp(&a.1));
    sorted
}

/// Trim output to fit within an approximate token budget.
/// Uses chars/4 as the token estimate.
pub fn trim_to_budget(output: &str, max_tokens: usize) -> String {
    let max_chars = max_tokens * 4;
    if output.len() <= max_chars {
        return output.to_string();
    }
    let truncated = &output[..max_chars];
    if let Some(pos) = truncated.rfind("\n## ") {
        format!(
            "{}\n\n*[Truncated to fit token budget]*\n",
            &output[..pos]
        )
    } else {
        format!("{}...\n\n*[Truncated to fit token budget]*\n", truncated)
    }
}

fn format_duration_human(seconds: i64) -> String {
    if seconds < 60 {
        format!("{seconds}s")
    } else if seconds < 3600 {
        format!("{}m{}s", seconds / 60, seconds % 60)
    } else {
        format!("{}h{}m", seconds / 3600, (seconds % 3600) / 60)
    }
}
