use std::env;
use std::fs;
use crate::config::Config;
use crate::db::Db;
use crate::error::Error;
use crate::workspace;

pub fn run(target: Option<String>, goal: String, scope: Option<String>) -> Result<(), Error> {
    let cwd = env::current_dir()?;
    let rt_dir = cwd.join(".redtrail");

    if rt_dir.exists() {
        eprintln!("workspace already exists in {}", cwd.display());
        return Ok(());
    }

    fs::create_dir_all(&rt_dir)?;

    let db = Db::open(workspace::db_path(&cwd).to_str().unwrap())?;

    let session_name = cwd.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("default")
        .to_string();
    let session_id = uuid::Uuid::new_v4().to_string();

    db.conn().execute(
        "INSERT INTO sessions (id, name, target, scope, goal) VALUES (?1, ?2, ?3, ?4, ?5)",
        rusqlite::params![session_id, session_name, target, scope, goal],
    ).map_err(|e| Error::Db(e.to_string()))?;

    let mut ws_config = String::new();
    if target.is_some() || goal != "general" {
        ws_config.push_str("[session]\n");
        if let Some(ref t) = target {
            ws_config.push_str(&format!("target = \"{t}\"\n"));
        }
        if goal != "general" {
            ws_config.push_str(&format!("goal = \"{goal}\"\n"));
        }
    }
    fs::write(workspace::config_path(&cwd), &ws_config)?;

    let config = Config::resolved(&cwd)?;
    let aliases: Vec<String> = config.tools.aliases.iter()
        .map(|tool| format!("alias {tool}='rt {tool}'"))
        .collect();
    let aliases_content = format!("# Generated by rt init\n{}\n", aliases.join("\n"));
    fs::write(workspace::aliases_path(&cwd), aliases_content)?;

    println!("workspace created: {}", cwd.display());
    println!("  session: {session_name}");
    if let Some(ref t) = target {
        println!("  target: {t}");
    }
    println!("\nactivate with: eval \"$(rt env)\"");

    Ok(())
}
