use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceRecord {
    pub id: String,
    pub timestamp: u64,
    pub specialist: String,
    #[serde(default)]
    pub task_id: Option<u32>,
    pub tool_name: String,
    pub tool_input: String,
    pub tool_output: String,
    #[serde(default)]
    pub model_delta: Option<String>,
    #[serde(default)]
    pub hypothesis_id: Option<String>,
    #[serde(default)]
    pub finding_ref: Option<String>,
    #[serde(default)]
    pub poc_script: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EvidenceChain {
    pub records: Vec<EvidenceRecord>,
    #[serde(default)]
    pub session_id: String,
    #[serde(default)]
    pub target_description: String,
}

impl EvidenceChain {
    pub fn new(session_id: &str, target_description: &str) -> Self {
        Self {
            records: Vec::new(),
            session_id: session_id.to_string(),
            target_description: target_description.to_string(),
        }
    }

    pub fn record(&mut self, record: EvidenceRecord) {
        self.records.push(record);
    }

    pub fn records_for_hypothesis(&self, hypothesis_id: &str) -> Vec<&EvidenceRecord> {
        self.records
            .iter()
            .filter(|r| r.hypothesis_id.as_deref() == Some(hypothesis_id))
            .collect()
    }

    pub fn records_with_findings(&self) -> Vec<&EvidenceRecord> {
        self.records
            .iter()
            .filter(|r| r.finding_ref.is_some())
            .collect()
    }

    pub fn records_for_task(&self, task_id: u32) -> Vec<&EvidenceRecord> {
        self.records
            .iter()
            .filter(|r| r.task_id == Some(task_id))
            .collect()
    }

    pub fn export_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    pub fn export_poc_scripts(&self) -> Vec<PocScript> {
        let mut scripts = Vec::new();

        let mut by_hypothesis: std::collections::HashMap<String, Vec<&EvidenceRecord>> =
            std::collections::HashMap::new();
        for record in &self.records {
            if let Some(ref hyp_id) = record.hypothesis_id {
                by_hypothesis
                    .entry(hyp_id.clone())
                    .or_default()
                    .push(record);
            }
        }

        for (hyp_id, records) in &by_hypothesis {
            let mut lines = Vec::new();
            lines.push("#!/bin/bash".to_string());
            lines.push(format!("# PoC for hypothesis: {hyp_id}"));
            lines.push(format!("# Target: {}", self.target_description));
            lines.push(format!("# Session: {}", self.session_id));
            lines.push("# Generated by redtrail".to_string());
            lines.push(String::new());

            for record in records {
                if let Some(ref poc) = record.poc_script {
                    lines.push(format!(
                        "# Step: {} via {}",
                        record.tool_name, record.specialist
                    ));
                    lines.push(poc.clone());
                    lines.push(String::new());
                }
            }

            if lines.len() > 6 {
                scripts.push(PocScript {
                    name: format!("poc_{hyp_id}.sh"),
                    hypothesis_id: Some(hyp_id.clone()),
                    finding_ref: records.iter().find_map(|r| r.finding_ref.clone()),
                    content: lines.join("\n"),
                });
            }
        }

        for record in &self.records {
            if record.hypothesis_id.is_none()
                && record.finding_ref.is_some()
                && let Some(ref poc) = record.poc_script
            {
                let finding = record.finding_ref.as_deref().unwrap_or("unknown");
                scripts.push(PocScript {
                    name: format!("poc_{}.sh", record.id),
                    hypothesis_id: None,
                    finding_ref: Some(finding.to_string()),
                    content: format!(
                        "#!/bin/bash\n# PoC for finding: {finding}\n# Target: {}\n# Session: {}\n# Generated by redtrail\n\n# Step: {} via {}\n{poc}\n",
                        self.target_description, self.session_id, record.tool_name, record.specialist
                    ),
                });
            }
        }

        scripts
    }

    pub fn len(&self) -> usize {
        self.records.len()
    }

    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PocScript {
    pub name: String,
    #[serde(default)]
    pub hypothesis_id: Option<String>,
    #[serde(default)]
    pub finding_ref: Option<String>,
    pub content: String,
}
